### ISSUE TITLE
Incompatible w/ ChromatiCraft

### ISSUE THREAD

**Issue by Judahmeek** [delvr/Repose#8]
Wishing you luck. Let me know if there's anything I can do to help.

Minecraft `1.7.10`
Repose `1.2.4`
ChromatiCraft `V16d`

```[22:56:51] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:56:51] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:56:51] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[22:56:51] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[22:56:51] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\DarthMakeral\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[22:56:51] [main/WARN] [FML]: The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:51] [main/INFO] [ArsMagica2]: Core initializing...stand back!  I'm going to try MAGIC!
[22:56:51] [main/WARN] [FML]: The coremod da3dsoul.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:51] [main/INFO] [FML]: [AppEng] Core Init
[22:56:51] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod cofh.tweak.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod farseek.core.FarseekCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/INFO] [FML]: Loading tweaker fastcraft.Tweaker from fastcraft-1.23.jar
[22:56:52] [main/INFO] [FML]: Loading tweaker forestry.shade.javacheck.Java7Checker from forestry_1.7.10-4.2.16.64.jar
[22:56:52] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod mariculture.fishery.VanillaOverride does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/ERROR] [FML]: Coremod DepLoader: Unable to class load the plugin xreliquary.common.asm.DepLoader
java.lang.ClassNotFoundException: xreliquary.common.asm.DepLoader
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:56:52] [main/WARN] [FML]: The coremod repose.core.ReposeCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/WARN] [FML]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:56:52] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:56:52] [main/INFO] [LaunchWrapper]: Loading tweak class name fastcraft.Tweaker
[22:56:52] [main/INFO] [LaunchWrapper]: Loading tweak class name forestry.shade.javacheck.Java7Checker
[22:56:52] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[22:56:52] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:56:52] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:56:52] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:56:54] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class am2.preloader.AccessTransformers
java.lang.IllegalArgumentException: resource AM2_at.cfg not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[guava-17.0.jar:?]
	at com.google.common.io.Resources.getResource(Resources.java:229) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:118) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at am2.preloader.AccessTransformers.<init>(AccessTransformers.java:10) ~[AccessTransformers.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at java.lang.Class.newInstance(Class.java:438) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:108) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:56:54] [main/INFO] [ArsMagica2]: Core: Located DragonAPI in DragonAPI 1.7.10 V16d.jar
[22:56:54] [main/INFO] [ArsMagica2]: Core: Located Thaumcraft in Thaumcraft-1.7.10-4.2.3.5.jar
[22:56:54] [main/INFO] [ArsMagica2]: Core: Located Thaumcraft in ThaumcraftMobAspects-1.7.2-2A.jar
[22:56:54] [main/INFO] [ArsMagica2]: Core: Located Thaumcraft in thaumcraftneiplugin-1.7.10-1.7a.jar
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [da3dsoulASMFix]: Obfuscated environment detected
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [IC2-core]: Loaded library EJML-core-0.26.jar.
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class forestry.shade.javacheck.Java7Checker
[22:56:54] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[22:56:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:55] [main/INFO] [FML]: Java Version: [8, 0, 25]
[22:56:55] [main/INFO] [FML]: Heap memory allocation: 4096000000
[22:56:55] [main/INFO] [FML]: 12 Java arguments present: [-Xmx4096m, -Duser.country=US, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Dminecraft.applet.TargetDirectory=C:\Users\DarthMakeral\Documents\Curse\Minecraft\Instances\Tinks, -Djava.library.path=C:\Users\DarthMakeral\Documents\Curse\Minecraft\Install\versions\forge-10.13.4.1614\forge-10.13.4.1614-natives-45713993814200, -Dos.name=Windows 10, -XX:PermSize=256m, -Dfml.ignoreInvalidMinecraftCertificates=true, -Dos.version=10.0, -Dfml.ignorePatchDiscrepancies=true, -Xms256m, -Duser.language=en]
[22:56:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:56] [main/ERROR] [FML]: Unable to determine registrant mod for cofh.tweak.asmhooks.EventHandler@281ce6bb. This is a critical error and should be impossible
java.lang.Throwable
	at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:55) [EventBus.class:?]
	at cofh.tweak.asm.LoadingPlugin.injectData(LoadingPlugin.java:142) [CoFHTweaks-%5B1.7.10%5D1.1.2-89.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:119) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:56:56] [main/ERROR] [FML]: Unable to determine registrant mod for cofh.tweak.asmhooks.EventHandler@281ce6bb. This is a critical error and should be impossible
java.lang.Throwable
	at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:55) [EventBus.class:?]
	at cofh.tweak.asm.LoadingPlugin.injectData(LoadingPlugin.java:143) [CoFHTweaks-%5B1.7.10%5D1.1.2-89.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:119) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[22:56:56] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:56] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:56] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:56:56] [main/INFO] [LaunchWrapper]: Calling tweak class fastcraft.Tweaker
[22:56:56] [main/INFO] [FastCraft]: FastCraft loaded.
[22:56:56] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[22:56:56] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[22:56:56] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[22:56:56] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Running patcher MUSICTYPEEVENT [net.minecraft.client.Minecraft/bao]
[22:56:56] [main/INFO] [FML]: DRAGONAPI: OPTIFINE not detected.
[22:56:56] [main/INFO] [FML]: DRAGONAPI: LITELOADER not detected.
[22:56:56] [main/INFO] [FML]: DRAGONAPI: FASTCRAFT detected. Loading compatibility features.
[22:56:56] [main/INFO] [FML]: 		Note that some parts of the game, especially render and block changes, may error out.
[22:56:56] [main/INFO] [FML]: 		
[22:56:56] [main/INFO] [FML]: DRAGONAPI: VIVE not detected.
[22:56:56] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied MUSICTYPEEVENT [net.minecraft.client.Minecraft/bao] ASM handler!
[22:56:56] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Running patcher PUSHENTITYOUT [net.minecraft.entity.Entity/sa]
[22:56:56] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: DragonAPI: Successfully applied PUSHENTITYOUT [net.minecraft.entity.Entity/sa] ASM handler!
[22:56:57] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: ChromatiCraft: Patching class net.minecraft.entity.EntityLivingBase
[22:56:57] [main/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper]: ChromatiCraft: Successfully applied STOPSLOWFALL ASM handler!
[22:56:57] [main/ERROR] [FastCraft]: asm error net.minecraft.entity.EntityLivingBase 78d32a6f dr 9212d28e 0 1
[22:56:57] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.entity.EntityLivingBase
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-17.0.jar:?]
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94) ~[CoFHCore-%5B1.7.10%5D3.1.4-329.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.EntityLivingBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.4-329.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: asm error net.minecraft.entity.EntityLivingBase 78d32a6f dr 9212d28e 0 1
	at fastcraft.J.transform(F:64) ~[fastcraft-1.23.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5B1.7.10%5D3.1.4-329.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more
Exception in thread "main" [22:56:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[22:56:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[22:56:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[22:56:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[22:56:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:968)
[22:56:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[22:56:57] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Judahmeek** [comment]
Hmmm... Actually, I'm not sure what's incompatible with what. If I remove `repose`, no crash. If I keep `repose` and remove FastCraft, there's also no crash. Also, I noticed mentions of COFH in the stacktrace, so this might be related to https://github.com/CoFH/CoFHTweaks/pull/1/files somehow?

**Comment by delvr** [comment]
Thanks Judahmeek for reporting, I'll take a look and get back to you.

**Comment by delvr** [comment]
Farseek version 1.7.10-2.0 includes a coremod mechanic overhaul which might have resolved issues such as this one. Please re-test and let me know if this still occurs. Thanks!
